### ISSUE TITLE
Missing number of turns for activated multi-skill

### ISSUE THREAD

**Issue by Sylvie** [Wisdomb33r/ffch-admin#137] opened 2019-11-14 21:50 UTC
230972 Lame rebelle (active 509811)

Our description misses the point that the 4 uses or Chaos End are available for 1 turn

**Comment by Wisdomb33r** [comment] 2019-11-22 14:21
Duplicate of #135, the reason the multi-skill parsing is wrong is due to the fact the skill has no cost at all (0 MP, 0 EP, 0 LB).

**Closed** 2019-11-22 16:15 UTC
Labels: bug, duplicate
